### PR TITLE
Backport waila stuff

### PR DESCRIPTION
**Pull request by mitchej123**
I backported some waila features for p2p tunnels from 1.12+ (frequencies, status, etc) for use on GTNH, and thought others might find it useful.

### CODE REVIEW

**Comment by xsun2001** [comment]
Thanks a lot !
I noticed that you have changed the version of AE back to 6.  Is it necessary for my repo?

**Comment by mitchej123** [comment]
@bartimaeusnek Looks like I grabbed your commit, can you  speak to why that was necessary or should I remove it for this PR?

**Comment by mitchej123** [comment]
No answer from bart, reverted it for this PR.

**Comment by xsun2001** [comment]
Alright. Thanks a lot for your help anyway.

**Comment by bartimaeusnek** [comment]
the comment in the gradle.properties states it; without v6, *some* additions to Applied Energistics need to be updated aswell. dont question me which ones, but they dont work/crash. Havent seen the ping tbh.

**Pull request merged**
